[tool.poetry]
name = "server"
version = "0.1.0"
description = ""
authors = ["Zheqi Liu <zliu2@godaddy.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
